# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vendelo_development
  host: "172.18.0.2" # IP del contenedor de PostgreSQL
  port: 5432
  username: postgres  
  password: postgres

test:
  <<: *default
  database: vendelo_test
  host: "172.18.0.2" # IP del contenedor de PostgreSQL
  port: 5432
  username: postgres  
  password: postgres

production:
  <<: *default
  database: vendelo_production
  username: vendelo
  password: <%= ENV["VENDELO_DATABASE_PASSWORD"] %>
